"""Freeze the active environment into a platform-named lock file.

Run from the repository root, with the project's venv active:

    python scripts/freeze_lock.py

What a lock file is
-------------------
``requirements.txt`` pins the packages we chose. Those packages pull in
further packages of their own (scipy, pillow, sympy, ...) which are *not*
pinned there — pip resolves them at install time. A **lock file** records the
exact version of *everything* actually installed, so an environment can be
rebuilt identically, byte for byte, later — even if some transitive package
publishes a new release in the meantime.

Why one lock per platform, not a single ``requirements.lock``
-------------------------------------------------------------
A freeze is only valid for the platform that produced it. SegAudit
deliberately runs two dependency lanes (Intel Macs use the last PyTorch built
for that hardware), and even between the modern platforms transitive versions
can differ. So locks are written to ``locks/`` with the platform in the file
name, e.g. ``requirements-lock-macos-x86_64-py3.11.txt``, and each records
its origin in a header. See ``locks/README.md``.

The written file starts with the PyTorch CPU index as an extra index, so that
``pip install -r locks/<file>`` can resolve CPU builds of torch in one step.
"""

from __future__ import annotations

import datetime
import platform
import subprocess
import sys
from pathlib import Path

LOCKS_DIR = Path(__file__).resolve().parent.parent / "locks"


def lane() -> str:
    """Human name for this machine's dependency lane."""
    if sys.platform == "darwin" and platform.machine() == "x86_64":
        return "intel-mac (torch 2.2 lane)"
    return "current (torch 2.13 lane)"


def lock_filename() -> str:
    os_name = {"darwin": "macos", "win32": "windows"}.get(sys.platform, "linux")
    machine = platform.machine().lower()
    py = f"py{sys.version_info.major}.{sys.version_info.minor}"
    return f"requirements-lock-{os_name}-{machine}-{py}.txt"


def frozen_requirements() -> str:
    """`pip freeze` of the active environment, without the editable segaudit line."""
    out = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--exclude-editable"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return out.strip() + "\n"


def main() -> int:
    if sys.prefix == sys.base_prefix:
        print("Refusing to freeze: no virtual environment is active.")
        print("Activate the project's .venv first (see the setup guide), then rerun.")
        return 1

    LOCKS_DIR.mkdir(exist_ok=True)
    target = LOCKS_DIR / lock_filename()
    header = (
        f"# Lock file generated by scripts/freeze_lock.py\n"
        f"# date:      {datetime.date.today().isoformat()}\n"
        f"# python:    {sys.version.split()[0]}\n"
        f"# platform:  {platform.platform()}\n"
        f"# lane:      {lane()}\n"
        f"# rebuild:   python -m pip install -r locks/{target.name}\n"
        f"#            (in a fresh venv on the SAME platform and Python minor version)\n"
        "--extra-index-url https://download.pytorch.org/whl/cpu\n"
    )
    target.write_text(header + frozen_requirements(), encoding="utf-8")
    print(f"Wrote {target.relative_to(Path.cwd()) if target.is_relative_to(Path.cwd()) else target}")
    print("Commit it if you want this environment to be rebuildable by others.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
